In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
sns.set_theme(style="whitegrid")

# Load the dataset
file_path = 'Multi_Touch_Marketingg.csv'
df = pd.read_csv(file_path)

print(f"Dataset loaded successfully with {df.shape[0]} rows and {df.shape[1]} columns.\n")
df.head()

Dataset loaded successfully with 1050 rows and 21 columns.

,Customer_ID,Touchpoint_Date,Touchpoint_Order,Channel,Touchpoint_Type,Device,Country,Customer_Segment,Product_Category,Product_Name,...,Conversion_Flag,Revenue,Customer_Converted,Touchpoints_Per_Customer,First_Touch_Flag,Last_Touch_Flag,Linear_Attribution_Share,Linear_Attributed_Revenue,Attributed_Profit,ROI_Percent
0,CUST1001,05-02-2026,1,Facebook Ads,App Visit,Tablet,India,New Customer,Home Loan,Home Loan,...,0,0.0,0,3,1,0,0.00,0.00,-61.92,-100.00
1,CUST1001,13-02-2026,2,YouTube,Email,Tablet,India,New Customer,Home Loan,Home Loan,...,0,0.0,0,3,0,0,0.00,0.00,-461.21,-100.00
2,CUST1001,12-02-2026,3,YouTube,App Visit,Tablet,India,New Customer,Home Loan,Home Loan,...,0,0.0,0,3,0,1,0.00,0.00,-369.53,-100.00
3,CUST1002,10-02-2026,1,Organic Search,Social Ad,Mobile,India,Premium,Insurance,Health Insurance,...,0,0.0,1,4,1,0,0.25,3328.88,3309.88,17420.42
4,CUST1002,18-02-2026,2,Organic Search,Website Visit,Mobile,India,Premium,Insurance,Health Insurance,...,0,0.0,1,4,0,0,0.25,3328.88,3315.65,25061.60

In [3]:
# Load the data set showing data types, columns , range index and checking the any null value in whole data set


import pandas as pd
import os

# Check files in current directory or find Multi_Touch_Marketingg.csv
files = [f for f in os.listdir('.') if f.endswith('.csv')]
print("CSV files:", files)

# Read the file
df = pd.read_csv('Multi_Touch_Marketingg.csv')
print("\nDataset Info:")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())

CSV files: ['Ecommerce_Transactions_Clean.csv', 'Multi_Touch_Marketingg.csv']

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer_ID                1050 non-null   object
 1   Touchpoint_Date            1050 non-null   object
 2   Touchpoint_Order           1050 non-null   int64
 3   Channel                    1050 non-null   object
 4   Touchpoint_Type            1050 non-null   object
 5   Device                     1050 non-null   object
 6   Country                    1050 non-null   object
 7   Customer_Segment           1050 non-null   object
 8   Product_Category           1050 non-null   object
 9   Product_Name               1050 non-null   object
 10  Cost                       1050 non-null   float64
 11  Conversion_Flag            1050 non-null   int64
 12  Revenue                    1050 non-null   float64
 13  Customer_Converted         1050 non-null   int64
 14  Touchpoints_Per_Customer   1050 non-null   int64
 15  First_Touch_Flag           1050 non-null   int64
 16  Last_Touch_Flag            1050 non-null   int64
 17  Linear_Attribution_Share   1050 non-null   float64
 18  Linear_Attributed_Revenue  1050 non-null   float64
 19  Attributed_Profit          1050 non-null   float64
 20  ROI_Percent                1050 non-null   float64
dtypes: float64(6), int64(6), object(9)
memory usage: 172.4+ KB
None

First 5 rows:
  Customer_ID Touchpoint_Date  Touchpoint_Order         Channel  \
0    CUST1001      05-02-2026                 1    Facebook Ads
1    CUST1001      13-02-2026                 2         YouTube
2    CUST1001      12-02-2026                 3         YouTube
3    CUST1002      10-02-2026                 1  Organic Search
4    CUST1002      18-02-2026                 2  Organic Search

  Touchpoint_Type  Device Country Customer_Segment Product_Category  \
0       App Visit  Tablet   India     New Customer        Home Loan
1           Email  Tablet   India     New Customer        Home Loan
2       App Visit  Tablet   India     New Customer        Home Loan
3       Social Ad  Mobile   India          Premium        Insurance
4   Website Visit  Mobile   India          Premium        Insurance

       Product_Name  ...  Conversion_Flag  Revenue  Customer_Converted  \
0         Home Loan  ...                0      0.0                   0
1         Home Loan  ...                0      0.0                   0
2         Home Loan  ...                0      0.0                   0
3  Health Insurance  ...                0      0.0                   1
4  Health Insurance  ...                0      0.0                   1

   Touchpoints_Per_Customer  First_Touch_Flag  Last_Touch_Flag  \
0                         3                 1                0
1                         3                 0                0
2                         3                 0                1
3                         4                 1                0
4                         4                 0                0

   Linear_Attribution_Share  Linear_Attributed_Revenue  Attributed_Profit  \
0                      0.00                       0.00             -61.92
1                      0.00                       0.00            -461.21
2                      0.00                       0.00            -369.53
3                      0.25                    3328.88            3309.88
4                      0.25                    3328.88            3315.65

   ROI_Percent
0      -100.00
1      -100.00
2      -100.00
3     17420.42
4     25061.60

[5 rows x 21 columns]

In [4]:
# Check duplicate records for the same Customer ID, Date, and Touchpoint Order
initial_count = len(df)
duplicate_count = df.duplicated(subset=['Customer_ID', 'Touchpoint_Date', 'Touchpoint_Order']).sum()

print(f"Found {duplicate_count} duplicate records.")

# Drop exact duplicate interactions
df_clean = df.drop_duplicates(subset=['Customer_ID', 'Touchpoint_Date', 'Touchpoint_Order']).copy()

# Sort records chronologically by Customer ID and Touchpoint Order
df_clean = df_clean.sort_values(by=['Customer_ID', 'Touchpoint_Order']).reset_index(drop=True)

print(f"Cleaned dataset shape: {df_clean.shape} (Removed {initial_count - len(df_clean)} rows)")

Found 0 duplicate records.
Cleaned dataset shape: (1050, 21) (Removed 0 rows)

In [5]:
# Convert 'Touchpoint_Date' to standard datetime format (DD-MM-YYYY)
df['Touchpoint_Date'] = pd.to_datetime(df['Touchpoint_Date'], format='%d-%m-%Y', errors='coerce')

# Standardize to UTC timezone
df['Touchpoint_Date_UTC'] = df['Touchpoint_Date'].dt.tz_localize('UTC')

print("Timestamp format standardized to UTC:")
df[['Customer_ID', 'Touchpoint_Date', 'Touchpoint_Date_UTC']].head()

Timestamp format standardized to UTC:

  Customer_ID Touchpoint_Date       Touchpoint_Date_UTC
0    CUST1001      2026-02-05 2026-02-05 00:00:00+00:00
1    CUST1001      2026-02-13 2026-02-13 00:00:00+00:00
2    CUST1001      2026-02-12 2026-02-12 00:00:00+00:00
3    CUST1002      2026-02-10 2026-02-10 00:00:00+00:00
4    CUST1002      2026-02-18 2026-02-18 00:00:00+00:00

In [6]:
import pandas as pd

# Define tracking and UTM parameters to clean
tracking_cols = ['Channel', 'Touchpoint_Type', 'Device']

# 1. Check which columns exist in the DataFrame
existing_cols = [col for col in tracking_cols if col in df.columns]

# 2. Fill missing values across existing tracking columns
df[existing_cols] = df[existing_cols].fillna('Unknown / Direct')

# 3. Verify cleanup and print non-null counts for confirmation
print("=== UTM & Tracking Cleanup Summary ===")
print(df[existing_cols].isnull().sum().to_frame(name="Remaining Nulls"))
print("\nUTM Parameters & Channel fields sanitized successfully.")

=== UTM & Tracking Cleanup Summary ===
                 Remaining Nulls
Channel                        0
Touchpoint_Type                0
Device                         0

UTM Parameters & Channel fields sanitized successfully.

In [11]:
# Define tracking and UTM parameters
tracking_cols = ['Channel', 'Touchpoint_Type', 'Device']

# Filter only columns that exist in the DataFrame
existing_cols = [col for col in tracking_cols if col in df.columns]

# Impute missing values across all existing tracking columns in one step
df[existing_cols] = df[existing_cols].fillna('Unknown / Direct')

# Print verification summary
print("=== UTM & Tracking Parameters Sanitized ===")
print(f"Columns processed: {existing_cols}")
print(f"Remaining null values:\n{df[existing_cols].isnull().sum()}")

=== UTM & Tracking Parameters Sanitized ===
Columns processed: ['Channel', 'Touchpoint_Type', 'Device']
Remaining null values:
Channel            0
Touchpoint_Type    0
Device             0
dtype: int64